---
title: Cress Egg Heads
hero_image: images/banner.png
description: A fun time-lapse photography project with the Raspberry Pi Camera Board
and cress seed
original_url: https://raspberrypi.org/learning/cress-egg-heads
theme: green
duration: 3
listed: true
ingredient: false
copyedit: true
curriculum: 2, design-0, programming-2, phys-comp-1, manufacture-1, community-0
interests: photography
technologies: python, pi-camera
site_areas: projects
hardware: pi-camera
software: python
version: 3
last_tested: 2017-01-01
steps: 
- title: Introduction
- title: What you will need
- title: Cress Egg Heads
- title: Making a cress egg head
- title: Setting up the Camera Module
- title: Taking a test shot
- title: Setting up for the real time-lapse
- title: Creating a time-lapse sequence
- title: Letting the cress grow and looking after it
- title: Creating a time-lapse video
- title: What next?