---
title: Cress Egg Heads
hero_image: images/banner.png
description: A fun time-lapse photography project with the Raspberry Pi Camera Board
  and cress seed
original_url: https://raspberrypi.org/learning/cress-egg-heads
theme: green
duration: 3
listed: true
ingredient: false
copyedit: true
curriculum: 2, design-0, programming-2, phys-comp-1, manufacture-1, community-0
interests: photography
technologies: python, pi-camera
site_areas: projects
hardware: pi-camera
software: python
version: 3
last_tested: 2020-09-01
steps:
- title: Introduction
- title: What is a time-lapse?
- title: Grow the cress
  completion:
  - engaged
- title: Take a test shot
- title: Setting up for a time-lapse
- title: Creating a time-lapse sequence
  completion:
  - internal
- title: What next?
